services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT_BACKEND: ${PORT_BACKEND}
      PORT_FRONTEND: ${PORT_FRONTEND}
    depends_on:
      - mongo
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    environment:
      PORT_FRONTEND: ${PORT_FRONTEND}
      PORT_BACKEND: ${PORT_BACKEND}

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
      